# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Full Stack Toronto
email: comms@fsto.co
description: > # this means to ignore newlines until "baseurl:"
  Full Stack Toronto runs programs for developers and designers to advance
  their career and give back to the community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fsto.co" # the base hostname & protocol for your site
twitter_username: fullstackto
github_username:  fullstackto

# Build settings
markdown: kramdown
sass:
    style: :compressed
